server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
      
eureka:
  client:
  #是否将自己注册到Eureka服务中
    register-with-eureka: true
    #是否从Eureka服务中获取注册信息
    fetch-registry: true
    #Eureka注册中心的地址
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    #服务名称
    name: cloud-feign