server:
  port: 8803
  tomcat:
    uri-encoding: utf-8
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
        
spring:
  profiles:
    active: test
  application:
    name: SpringCloudConsume
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/master
    username: root
    password: 123456